server:
  port: 8082
spring:
  profiles.active: dev
  application:
    name: archive
  rabbitmq:
    addresses: ${RABBITMQ_NETWORK}:${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: ${TRACING_STATE:0}.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_TRACING_ENDPOINT}
