server:
  port: 8082
spring:
  profiles.active: dev
  application:
    name: archive
  data:
    mongodb:
      port: ${MONGODB_PORT}
      host: ${MONGODB_HOST}
      authentication-database: ${MONGODB_AUTHENTICATION_DB}
      username: ${MONGODB_USER}
      password: ${MONGODB_PASSWORD}
      database: ${MONGODB_DATABASE}
  rabbitmq:
    addresses: ${RABBITMQ_NETWORK}:${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: ${TRACING_STATE:0}.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_TRACING_ENDPOINT}
