spring:
  jpa:
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${OAUTH2_GOOGLE_CLIENT_ID}
            clientSecret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            redirectUri: "${PROD_BASE_URL}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: ${OAUTH2_FACEBOOK_CLIENT_ID}
            clientSecret: ${OAUTH2_FACEBOOK_CLIENT_SECRET}
            redirectUri: "${PROD_BASE_URL}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: ${TRACING_STATE:0}.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_TRACING_ENDPOINT}
---
spring:
  config:
    activate:
      on-profile: dev
  security:
    oauth2:
      client:
        registration:
          google:
            redirectUri: "${BASE_URL}/oauth2/callback/{registrationId}"
          facebook:
            redirectUri: "${BASE_URL}/oauth2/callback/{registrationId}"
---
logging:
  file:
    name: ${URL_LOGS:}/teach_ua.log
