server:
  port: 8086
spring:
  profiles.active: dev
  application:
    name: user
  datasource:
    driver-class-name: org.postgresql.Driver
    default-schema: user_schema
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: user_schema
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USER_EMAIL}
    password: ${SEND_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
        transport.protocol: smtp

management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: ${TRACING_STATE:0}.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_TRACING_ENDPOINT}
