spring:
  datasource:
    url: ${PROD_DATASOURCE_URL}?currentSchema=user_schema
    username: ${PROD_DATASOURCE_USER}
    password: ${PROD_DATASOURCE_PASSWORD}

application:
  jwt:
    access:
      key: ${JWT_ACCESS_SECRET_KEY}/prod
      expirationInMinutes: 30
    refresh:
      key: ${JWT_REFRESH_SECRET_KEY}/prod
      expirationInDays: 3
  baseURL: ${PROD_BASE_URL}
