services:
  teachua_postgres:
    image: postgres
    container_name: teachua_postgres
    env_file:
      - TeachUa.env
    volumes:
      - postgres:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - teachua_postgres
    restart: unless-stopped

  teachua_main-service:
    image: bnazar00/teachua_main-service:latest
    container_name: teachua_main-service
    ports:
      - "8080:8080"
    env_file:
      - TeachUa.env
    networks:
      - spring
      - teachua_postgres
    depends_on:
      - teachua_postgres

networks:
  teachua_postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
