services:
  teachua_postgres:
    image: postgres
    container_name: teachua_postgres
    env_file:
      - TeachUa-docker.env
    volumes:
      - postgres:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - teachua_postgres
    restart: unless-stopped

  teachua_nginx:
    image: nginx
    container_name: teachua_nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/security_filter.conf:/etc/nginx/security_filter.conf
      - ./nginx/security_admin_filter.conf:/etc/nginx/security_admin_filter.conf
    networks:
      - spring
    depends_on:
      - teachua_main-service
      - teachua_user
      - teachua_club
      - teachua_question
      - teachua_certificate

  teachua_zipkin:
    image: openzipkin/zipkin
    container_name: teachua_zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

  teachua_main-service:
    image: bnazar00/teachua_main-service:latest
    container_name: teachua_main-service
    ports:
      - "8081:8081"
    env_file:
      - TeachUa-docker.env
    networks:
      - spring
      - teachua_postgres
    depends_on:
      - teachua_postgres
      - teachua_zipkin

  teachua_user:
    image: bnazar00/teachua_user:latest
    container_name: teachua_user
    ports:
      - "8086:8086"
    env_file:
      - TeachUa-docker.env
    networks:
      - spring
      - teachua_postgres
    depends_on:
      - teachua_postgres
      - teachua_zipkin

  teachua_club:
    image: bnazar00/teachua_club:latest
    container_name: teachua_club
    ports:
      - "8091:8091"
    env_file:
      - TeachUa-docker.env
    networks:
      - spring
      - teachua_postgres
    depends_on:
      - teachua_postgres
      - teachua_zipkin

  teachua_question:
    image: bnazar00/teachua_question:latest
    container_name: teachua_question
    ports:
      - "8096:8096"
    env_file:
      - TeachUa-docker.env
    networks:
      - spring
      - teachua_postgres
    depends_on:
      - teachua_postgres
      - teachua_zipkin

  teachua_certificate:
    image: bnazar00/teachua_certificate:latest
    container_name: teachua_certificate
    ports:
      - "8101:8101"
    env_file:
      - TeachUa-docker.env
    networks:
      - spring
      - teachua_postgres
    depends_on:
      - teachua_postgres
      - teachua_zipkin

networks:
  teachua_postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
