version: "3.8"

services:
  frontend:
    build: ../TeachUAClient
    container_name: teachUA_client
    ports:
      - "3000:80"
    depends_on:
      - teachua

  teachua:
    build: .
    container_name: teachUA
    env_file:
      - environment.env
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: teachUA_db
    environment:
      POSTGRES_USER: ${DEV2_DATASOURCE_USER}
      POSTGRES_PASSWORD: ${DEV2_DATASOURCE_PASSWORD}
      POSTGRES_DB: teachua
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  db-data:
