{
 "title": "Requests",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Simple information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Maximum of Current TomCat Users",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(tomcat_connections_current_connections[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System load average",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_load_average_1m", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tomcat Current Connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tomcat_connections_current_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Amount of requests with exceptions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{exception!=\"None\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Total Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "GET Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri!=\"/api/prometheus\", uri!=\"/api/signin\", method=\"GET\"}",
     "legendFormat": "{{uri}} Status={{status}} Outcome={{outcome}}"
    }
   ]
  },
  {
   "title": "GET Requests Increase",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{uri!=\"/api/prometheus\", uri!=\"/api/signin\", method=\"GET\"}[1m])",
     "legendFormat": "{{uri}} Status={{status}} Outcome={{outcome}}"
    }
   ]
  },
  {
   "title": "POST Requests",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri!=\"/api/prometheus\", uri!=\"/api/signin\", method=\"POST\"}",
     "legendFormat": "{{uri}} Status={{status}} Outcome={{outcome}}"
    }
   ]
  },
  {
   "title": "PUT Requests",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri!=\"/api/prometheus\", uri!=\"/api/signin\", method=\"PUT\"}",
     "legendFormat": "{{uri}} Status={{status}} Outcome={{outcome}}"
    }
   ]
  },
  {
   "title": "DELETE Requests",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri!=\"/api/prometheus\", uri!=\"/api/signin\", method=\"DELETE\"}",
     "legendFormat": "{{uri}} Status={{status}} Outcome={{outcome}}"
    }
   ]
  },
  {
   "title": "Sign In stats",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri=\"/api/signin\"}",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}