{
 "title": "TomCat Metrics",
 "time": { "from": "2023-02-20T11:13:32.445Z", "to": "2023-02-20T11:53:46.799Z" },
 "panels": [
  {
   "title": "tomcat_connections_config_max_connections",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tomcat_connections_config_max_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tomcat_connections_current_connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "tomcat_connections_current_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tomcat_global_request_seconds_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "tomcat_global_request_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tomcat_global_error_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "tomcat_global_error_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "tomcat_global_received_bytes_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 16 },
   "targets": [
    {
     "expr": "tomcat_global_received_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tomcat_connections_keepalive_current_connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 16 },
   "targets": [
    {
     "expr": "tomcat_connections_keepalive_current_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tomcat_cache_access_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "tomcat_cache_access_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "tomcat_cache_hit_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "tomcat_cache_hit_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "tomcat_threads_busy_threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "tomcat_threads_busy_threads", "legendFormat": "__auto" }
   ]
  }
 ]
}