server:
  port: 8091
spring:
  profiles.active: dev
  application:
    name: club
  datasource:
    driver-class-name: org.postgresql.Driver
    default-schema: club
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: club
  rabbitmq:
    addresses: ${RABBITMQ_HOST}:${RABBITMQ_PORT}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: ${TRACING_STATE:0}.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_TRACING_ENDPOINT}
