spring:
  datasource:
    url: ${PROD_DATASOURCE_URL}?currentSchema=certificate
    username: ${PROD_DATASOURCE_USER}
    password: ${PROD_DATASOURCE_PASSWORD}

application:
  baseURL: ${PROD_BASE_URL}
