server:
  port: 8101
spring:
  profiles.active: dev
  application:
    name: certificate
  datasource:
    driver-class-name: org.postgresql.Driver
    default-schema: certificate
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: certificate
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USER_EMAIL}
    password: ${SEND_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
        transport.protocol: smtp

application:
  api:
    credentials:
      service-account:
        clientEmail: ${SERVICE_ACCOUNT_CLIENT_EMAIL}
        privateKey: ${SERVICE_ACCOUNT_PRIVATE_KEY}
