name: Create_Docker_Images

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-backend-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout the repo (specific branch)
        uses: actions/checkout@v3
        with:
          ref: try_to_configure_independed_dockerfiles
      
      - name: Login to GitHub Packages
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.ACTION_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:latest

  build-and-push-client-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout external repo
        uses: actions/checkout@v3
        with:
          repository: ita-social-projects/TeachUAClient
          ref: add_docker

      - name: Login to GitHub Packages
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.ACTION_TOKEN }}
          
      - name: Build and push Docker image for cloned repo
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/ita-social-projects/TeachUAClient:latest
 
