name: Checkstyle
on: pull_request
jobs:
  build:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run check style with Maven
        run: mvn --batch-mode --update-snapshots validate
