name: Test and Check
on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    name: verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        
      - name: Directory location
        run: "pwd"
        
      - name: List files
        run: "ls -al"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Java version
        run: "java -version"

      #- name: Run tests with Maven
      #  run: mvn --batch-mode --update-snapshots verify -Dcheckstyle.skip
      
      - name: Copy results to the remote host over SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "checkstyle.xml"
          target: "/root/temp/"
          strip_components: 1
